

hello_dem:
	go run hello_dem.go

detailed_hello_dem:
	go run detailed_hello_dem.go

png_dem:
	go run png_dem.go

shadowed_dem:
	go run shadowed_dem.go

outline_dem:
	go run outline_dem.go

obj_dem:
	go run obj_dem.go