

hello_dem:
	go run hello_dem.go

hello_dem_detailed:
	go run hello_dem_detailed.go

outline_interpolation:
	go run outline_interpolation.go

write_to_png:
	go run write_to_png.go

write_to_png_with_shadow:
	go run write_to_png_with_shadow.go

write_to_obj:
	go run write_to_obj.go

write_to_txt:
	go run write_to_txt.go